### ISSUE TITLE
High level explanation of decodeData()

### ISSUE THREAD

**Issue by michaelimstepf** [miguelmota/ethereum-input-data-decoder#3]
This isn't really an issue but if you have 5 minutes, I'd be very keen to hear how the `decodeData` method works (high level explanation) and what the `ethereumjs-abi` library was created for. I'm new to Ethereum and I'm still struggling to wrap my head around the `input` field of transactions.

**Comment by miguelmota** [comment]
The application binary interface (ABI) describes the contract and provides an interface for encoding/decoding data in/out of the machine code. The executables in the Ethereum Virtual Machine (EVM) are in machine code, so we need a way for humans to be able to understand what the inputs/outputs are of the contract methods. This is where the ABI comes in. When you send a transaction using a library such as Web3JS, behind the scenes they are converting the inputs and method names to a encoded format that the EVM requires. This format is completely unreadable to humans, so these libraries facilitate that. When you go to etherscan, you can see the encoded data that was used as inputs for method calls. To decode that in order to reveal the actual inputs values then that's where `ethereumjs-abi` comes in to do the decoding. But in order to decode you must have the ABI available. The library `ethereum-input-data-decoder` is a thin wrapper around that which compares the encoded methods of the ABI to the encoded data you passed it, in order to determine the input types and values.
